// <auto-generated />
namespace MusicPickerService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class OptionalGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OptionalGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "201506142239537_OptionalGenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
